### ISSUE TITLE
multipart/form-data

### ISSUE THREAD

**Issue by brad7100** [MadeiraData/ClrHttpRequest#3]
Just wondering if it is possible to post multipart/form-data using this CLR.

**Comment by EitanBlumin** [comment]
Yes, you can.
You can add a header called "Content-Type" with a value of "multipart/form-data" (or any other content type, as needed).

Notice that even in the main example in the README, there's this code snippet that makes use of the "Content-Type" header:

```
DECLARE @headers NVARCHAR(4000) = '<Headers><Header Name="Content-Type">application/json</Header><Header Name="Authorization-Basic-Credentials">' + @credentials + '</Header></Headers>'
```

Do the same, but instead of "application/json", use "multipart/form-data".

**Comment by brad7100** [comment]
Thank you for the response.  I tried that first but wasn’t able to get it to work when the data included varbinary.  The multipart form data includes a Pdf file.

**Comment by EitanBlumin** [comment]
I think it should work if you use POST method, and you'd have to somehow convert the varbinary into a string (because that's the data type that the method accepts).

Which error are you getting exactly?
Does it work for you if you send something which is not varbinary?
